namespace ReactorSoftInterlock.Wpf;

public static class UiText
{
    private static readonly Dictionary<string, Dictionary<string, string>> Texts = new()
    {
        ["en"] = new()
        {
            ["app.title"] = "G2000 Temperature Soft Interlock",
            ["app.subtitle"] = "HikmicroAnalyzer OCR -> 90 C trip -> USB relay interlock",
            ["label.status"] = "Status:",
            ["group.temperature"] = "Temperature",
            ["group.controls"] = "Controls",
            ["group.configuration"] = "Configuration",
            ["group.chart"] = "Temperature Trend",
            ["button.selectRoi"] = "Select ROI",
            ["button.start"] = "Start",
            ["button.stop"] = "Stop",
            ["button.reset"] = "Reset",
            ["button.testRelay"] = "Test Relay Stop",
            ["button.testRelayReset"] = "Test Relay Restore",
            ["button.export"] = "Export CSV",
            ["button.guide"] = "Open Lab Guide",
            ["button.save"] = "Save Settings",
            ["label.window"] = "Window",
            ["label.threshold"] = "Threshold C",
            ["label.tesseract"] = "Tesseract",
            ["label.interval"] = "Interval ms",
            ["label.com"] = "COM Port",
            ["label.baud"] = "Baud",
            ["label.stopHex"] = "Stop command",
            ["label.resetHex"] = "Reset command",
            ["label.language"] = "Language",
            ["label.recovery"] = "Recovery C",
            ["label.stable"] = "Stable sec",
            ["check.dryRun"] = "Dry run relay",
            ["check.autoReset"] = "Auto reset",
            ["grid.time"] = "Time",
            ["grid.temp"] = "Temp C",
            ["grid.status"] = "Status",
            ["grid.relay"] = "Relay",
            ["grid.reason"] = "Reason",
            ["grid.roi"] = "ROI",
            ["footer.ready"] = "Ready.",
            ["footer.monitoringStarted"] = "Monitoring started.",
            ["footer.monitoringStopped"] = "Monitoring stopped.",
            ["footer.settingsSaved"] = "Settings saved",
            ["footer.roiSaved"] = "ROI saved",
            ["footer.resetComplete"] = "Reset complete",
            ["footer.relayTestComplete"] = "Relay test completed",
            ["footer.relayResetComplete"] = "Relay restore completed",
            ["footer.csvExported"] = "CSV exported",
            ["footer.tripped"] = "TRIPPED: relay stop command sent.",
            ["footer.lastSample"] = "Last sample",
            ["message.resetBlocked"] = "Reset is allowed only after a valid temperature below the threshold is read.",
            ["message.resetBlockedTitle"] = "Reset blocked",
            ["message.setupRequiredTitle"] = "Setup required",
            ["message.tesseractMissing"] = "Tesseract OCR was not found at '{0}'. Put a full offline Tesseract folder under offline-deps\\tesseract, or set Tesseract to the full path of tesseract.exe.",
            ["message.roiMissing"] = "ROI is not configured. Open HikmicroAnalyzer, keep the temperature text visible, then click Select ROI and mark only the maximum temperature text.",
            ["message.hikmicroMissing"] = "Could not find a visible HikmicroAnalyzer window matching '{0}'. Open HikmicroAnalyzer, do not minimize it, and check the Window field.",
            ["message.comMissing"] = "COM port '{0}' was not found. Open Windows Device Manager, expand Ports (COM & LPT), plug the USB relay in again, and enter the visible COMx value.",
            ["message.hexMissing"] = "{0} is empty. For the DSD TECH SH-UR04A, use ASCII AT commands such as AT+CH1=0 and AT+CH1=1.",
            ["message.hexInvalid"] = "{0} is not a valid relay command: {1}. Use ASCII AT commands such as AT+CH1=0, AT+CH1=1, or multiple lines for more than one channel.",
            ["status.Idle"] = "Idle",
            ["status.Monitoring"] = "Monitoring",
            ["status.NoReading"] = "No reading",
            ["status.Tripped"] = "Tripped",
            ["status.RelayTestFailed"] = "Relay test failed",
            ["chart.noData"] = "No valid temperature data yet",
            ["chart.threshold"] = "Trip",
            ["chart.recovery"] = "Recovery",
            ["guide.title"] = "Offline Lab Guide",
            ["guide.body"] = "Quick start\r\n\r\n1. Keep the relay driver package in offline-deps\\\\cp210x-driver.\r\n2. Install the CP210x driver from silabser.inf on the lab PC.\r\n3. Put a full offline Tesseract folder in offline-deps\\\\tesseract so that offline-deps\\\\tesseract\\\\tesseract.exe exists.\r\n4. Connect the DSD TECH SH-UR04A by USB. Confirm COM3 or update COM Port in the app.\r\n5. For the verified G2000 test path, wire I1 -> COM1 and I2 -> NO1 only. Leave the other interlock jumpers unchanged.\r\n6. In this relay-interlock-test branch, Stop command defaults to AT+CH1=0 and Reset command defaults to AT+CH1=1.\r\n\r\nRelay-only test\r\n\r\n1. Keep G2000 disconnected.\r\n2. Click Test Relay Stop. The relay should click and CH1 should open.\r\n3. Use a multimeter: CH1 ON means COM1-NO1 closed, CH1 OFF means COM1-NC1 closed.\r\n\r\nG2000 interlock test\r\n\r\n1. Power the G2000 off.\r\n2. Remove the I1-I2 jumper.\r\n3. Wire G2000 I1 -> COM1 and G2000 I2 -> NO1.\r\n4. Leave CH1 ON, then power the G2000 on. It should start normally and allow manual start.\r\n5. Turn CH1 OFF by clicking Test Relay Stop or by overheating logic later. The G2000 should show interlock Fehler and refuse start or stop HV.\r\n6. Turn CH1 back ON. The G2000 should return to normal and allow manual start again.\r\n\r\nOperational notes\r\n\r\n- The relay test area in this branch is for engineering validation only.\r\n- The software uses HikmicroAnalyzer screenshot OCR. Do not minimize or cover the HikmicroAnalyzer window.\r\n- If OCR is not ready, keep Dry run relay enabled.\r\n- Auto reset in the software only recloses the interlock path. It does not guarantee automatic plasma restart.\r\n- After lab validation, this branch-specific test UI can be removed.",
        },
        ["zh-CN"] = new()
        {
            ["app.title"] = "G2000 温度联控软锁",
            ["app.subtitle"] = "HikmicroAnalyzer OCR -> 90 C 停机 -> USB 继电器联锁",
            ["label.status"] = "状态：",
            ["group.temperature"] = "温度",
            ["group.controls"] = "控制",
            ["group.configuration"] = "配置",
            ["group.chart"] = "温度趋势",
            ["button.selectRoi"] = "框选 ROI",
            ["button.start"] = "开始",
            ["button.stop"] = "停止",
            ["button.reset"] = "复位",
            ["button.testRelay"] = "测试继电器停机",
            ["button.testRelayReset"] = "测试继电器恢复",
            ["button.export"] = "导出 CSV",
            ["button.guide"] = "打开实验室指南",
            ["button.save"] = "保存设置",
            ["label.window"] = "窗口",
            ["label.threshold"] = "停机阈值 C",
            ["label.tesseract"] = "Tesseract",
            ["label.interval"] = "间隔 ms",
            ["label.com"] = "COM 口",
            ["label.baud"] = "波特率",
            ["label.stopHex"] = "停止命令",
            ["label.resetHex"] = "复位命令",
            ["label.language"] = "语言",
            ["label.recovery"] = "恢复阈值 C",
            ["label.stable"] = "稳定秒数",
            ["check.dryRun"] = "继电器 Dry Run",
            ["check.autoReset"] = "自动复位",
            ["grid.time"] = "时间",
            ["grid.temp"] = "温度 C",
            ["grid.status"] = "状态",
            ["grid.relay"] = "继电器",
            ["grid.reason"] = "原因",
            ["grid.roi"] = "ROI",
            ["footer.ready"] = "就绪。",
            ["footer.monitoringStarted"] = "监控已开始。",
            ["footer.monitoringStopped"] = "监控已停止。",
            ["footer.settingsSaved"] = "设置已保存",
            ["footer.roiSaved"] = "ROI 已保存",
            ["footer.resetComplete"] = "复位完成",
            ["footer.relayTestComplete"] = "继电器测试完成",
            ["footer.relayResetComplete"] = "继电器恢复完成",
            ["footer.csvExported"] = "CSV 已导出",
            ["footer.tripped"] = "已 TRIP：继电器停机命令已发送。",
            ["footer.lastSample"] = "最新样本",
            ["message.resetBlocked"] = "只有读到低于阈值的有效温度后才允许复位。",
            ["message.resetBlockedTitle"] = "复位被阻止",
            ["message.setupRequiredTitle"] = "需要完成设置",
            ["message.tesseractMissing"] = "没有在“{0}”找到 Tesseract OCR。请把完整离线 Tesseract 文件夹放到 offline-deps\\tesseract，或者把 Tesseract 填成 tesseract.exe 的完整路径。",
            ["message.roiMissing"] = "ROI 还没有设置。请先打开 HikmicroAnalyzer，保持最高温文字可见，然后点击“框选 ROI”，只框最高温文字。",
            ["message.hikmicroMissing"] = "找不到匹配“{0}”的可见 HikmicroAnalyzer 窗口。请打开 HikmicroAnalyzer，不要最小化，并检查 Window 字段。",
            ["message.comMissing"] = "找不到 COM 口“{0}”。请打开 Windows 设备管理器，展开“Ports (COM & LPT)”，重新插入 USB 继电器，然后填写出现的 COMx。",
            ["message.hexMissing"] = "{0} 为空。对 DSD TECH SH-UR04A，请填写 ASCII AT 命令，例如 AT+CH1=0 和 AT+CH1=1。",
            ["message.hexInvalid"] = "{0} 不是有效继电器命令：{1}。请使用 ASCII AT 命令，例如 AT+CH1=0、AT+CH1=1；多路可换行填写。",
            ["status.Idle"] = "空闲",
            ["status.Monitoring"] = "监控中",
            ["status.NoReading"] = "无读数",
            ["status.Tripped"] = "已停机",
            ["status.RelayTestFailed"] = "继电器测试失败",
            ["chart.noData"] = "暂无有效温度数据",
            ["chart.threshold"] = "停机",
            ["chart.recovery"] = "恢复",
            ["guide.title"] = "离线实验室指南",
            ["guide.body"] = "快速开始\r\n\r\n1. 保持继电器驱动包在 offline-deps\\\\cp210x-driver。\r\n2. 在实验室电脑上对 silabser.inf 右键安装 CP210x 驱动。\r\n3. 把完整离线 Tesseract 文件夹放到 offline-deps\\\\tesseract，确保存在 offline-deps\\\\tesseract\\\\tesseract.exe。\r\n4. 用 USB 连接 DSD TECH SH-UR04A。确认是 COM3，或者在软件里修改 COM 口。\r\n5. 对当前已验证的 G2000 路径，只接 I1 -> COM1 和 I2 -> NO1，其他 interlock 跳线保持不变。\r\n6. 这个 relay-interlock-test 分支里，默认停止命令是 AT+CH1=0，默认复位命令是 AT+CH1=1。\r\n\r\n只测继电器\r\n\r\n1. 先不要接 G2000。\r\n2. 点击“测试继电器停机”。继电器应有动作，CH1 应断开。\r\n3. 用万用表确认：CH1 打开时 COM1-NO1 闭合，CH1 关闭时 COM1-NC1 闭合。\r\n\r\nG2000 interlock 测试\r\n\r\n1. 关闭 G2000 电源。\r\n2. 拆掉 I1-I2 短接片。\r\n3. 接线：G2000 I1 -> COM1，G2000 I2 -> NO1。\r\n4. 保持 CH1 打开，再给 G2000 上电。此时应恢复正常并允许手动启动。\r\n5. 把 CH1 关闭。G2000 应显示 interlock Fehler，并拒绝启动或停止 HV。\r\n6. 再把 CH1 打开。G2000 应恢复正常并允许再次手动启动。\r\n\r\n运行注意\r\n\r\n- 这个分支里的 interlock 测试区只给工程验证使用。\r\n- 软件通过 HikmicroAnalyzer 截图 OCR 工作，不要最小化，也不要遮挡 HikmicroAnalyzer。\r\n- 如果 OCR 还没准备好，保持继电器 Dry run。\r\n- 软件里的自动复位只表示重新闭合 interlock，不保证 plasma 自动重新启动。\r\n- 实验室验证完成后，这个分支专用测试 UI 可以删除。",
        },
        ["de"] = new()
        {
            ["app.title"] = "G2000 Temperatur-Soft-Interlock",
            ["app.subtitle"] = "HikmicroAnalyzer OCR -> 90 C Trip -> USB-Relais-Interlock",
            ["label.status"] = "Status:",
            ["group.temperature"] = "Temperatur",
            ["group.controls"] = "Steuerung",
            ["group.configuration"] = "Konfiguration",
            ["group.chart"] = "Temperaturverlauf",
            ["button.selectRoi"] = "ROI wählen",
            ["button.start"] = "Start",
            ["button.stop"] = "Stop",
            ["button.reset"] = "Reset",
            ["button.testRelay"] = "Relais-Stop testen",
            ["button.testRelayReset"] = "Relais wieder schließen",
            ["button.export"] = "CSV exportieren",
            ["button.guide"] = "Laborleitfaden öffnen",
            ["button.save"] = "Einstellungen speichern",
            ["label.window"] = "Fenster",
            ["label.threshold"] = "Trip C",
            ["label.tesseract"] = "Tesseract",
            ["label.interval"] = "Intervall ms",
            ["label.com"] = "COM-Port",
            ["label.baud"] = "Baud",
            ["label.stopHex"] = "Stop-Befehl",
            ["label.resetHex"] = "Reset-Befehl",
            ["label.language"] = "Sprache",
            ["label.recovery"] = "Recovery C",
            ["label.stable"] = "Stabil s",
            ["check.dryRun"] = "Relais Dry Run",
            ["check.autoReset"] = "Auto-Reset",
            ["grid.time"] = "Zeit",
            ["grid.temp"] = "Temp C",
            ["grid.status"] = "Status",
            ["grid.relay"] = "Relais",
            ["grid.reason"] = "Grund",
            ["grid.roi"] = "ROI",
            ["footer.ready"] = "Bereit.",
            ["footer.monitoringStarted"] = "Überwachung gestartet.",
            ["footer.monitoringStopped"] = "Überwachung gestoppt.",
            ["footer.settingsSaved"] = "Einstellungen gespeichert",
            ["footer.roiSaved"] = "ROI gespeichert",
            ["footer.resetComplete"] = "Reset abgeschlossen",
            ["footer.relayTestComplete"] = "Relaistest abgeschlossen",
            ["footer.relayResetComplete"] = "Relais wieder geschlossen",
            ["footer.csvExported"] = "CSV exportiert",
            ["footer.tripped"] = "TRIPPED: Relais-Stop-Befehl gesendet.",
            ["footer.lastSample"] = "Letzter Messwert",
            ["message.resetBlocked"] = "Reset ist erst nach einem gültigen Temperaturwert unterhalb des Schwellwerts erlaubt.",
            ["message.resetBlockedTitle"] = "Reset blockiert",
            ["message.setupRequiredTitle"] = "Einrichtung erforderlich",
            ["message.tesseractMissing"] = "Tesseract OCR wurde unter '{0}' nicht gefunden. Legen Sie einen vollständigen Offline-Tesseract-Ordner unter offline-deps\\tesseract ab oder tragen Sie den vollständigen Pfad zu tesseract.exe ein.",
            ["message.roiMissing"] = "ROI ist nicht eingerichtet. Öffnen Sie HikmicroAnalyzer, halten Sie den Temperaturtext sichtbar und wählen Sie mit ROI wählen nur den Maximaltemperatur-Text aus.",
            ["message.hikmicroMissing"] = "Kein sichtbares HikmicroAnalyzer-Fenster passend zu '{0}' gefunden. Öffnen Sie HikmicroAnalyzer, minimieren Sie es nicht und prüfen Sie das Feld Fenster.",
            ["message.comMissing"] = "COM-Port '{0}' wurde nicht gefunden. Öffnen Sie den Windows Geräte-Manager, erweitern Sie Ports (COM & LPT), stecken Sie das USB-Relais neu ein und tragen Sie den sichtbaren COMx-Wert ein.",
            ["message.hexMissing"] = "{0} ist leer. Für das DSD TECH SH-UR04A verwenden Sie ASCII-AT-Befehle wie AT+CH1=0 und AT+CH1=1.",
            ["message.hexInvalid"] = "{0} ist kein gültiger Relaisbefehl: {1}. Verwenden Sie ASCII-AT-Befehle wie AT+CH1=0, AT+CH1=1 oder mehrere Zeilen für mehrere Kanäle.",
            ["status.Idle"] = "Bereit",
            ["status.Monitoring"] = "Überwachung",
            ["status.NoReading"] = "Kein Messwert",
            ["status.Tripped"] = "Tripped",
            ["status.RelayTestFailed"] = "Relaistest fehlgeschlagen",
            ["chart.noData"] = "Noch keine gültigen Temperaturdaten",
            ["chart.threshold"] = "Trip",
            ["chart.recovery"] = "Recovery",
            ["guide.title"] = "Offline-Laborleitfaden",
            ["guide.body"] = "Schnellstart\r\n\r\n1. Das Relais-Treiberpaket in offline-deps\\\\cp210x-driver belassen.\r\n2. Auf dem Labor-PC den CP210x-Treiber per Rechtsklick auf silabser.inf installieren.\r\n3. Einen vollständigen Offline-Tesseract-Ordner nach offline-deps\\\\tesseract kopieren, sodass offline-deps\\\\tesseract\\\\tesseract.exe vorhanden ist.\r\n4. Das DSD TECH SH-UR04A per USB anschließen. COM3 bestätigen oder den COM-Port in der App anpassen.\r\n5. Für den bereits bestätigten G2000-Testpfad nur I1 -> COM1 und I2 -> NO1 verdrahten. Andere Interlock-Jumper unverändert lassen.\r\n6. In diesem Branch relay-interlock-test ist der Standard-Stop-Befehl AT+CH1=0 und der Standard-Reset-Befehl AT+CH1=1.\r\n\r\nNur Relais testen\r\n\r\n1. G2000 noch nicht anschließen.\r\n2. Auf \"Relais-Stop testen\" klicken. Das Relais soll schalten und CH1 soll öffnen.\r\n3. Mit dem Multimeter prüfen: Bei CH1 EIN ist COM1-NO1 geschlossen, bei CH1 AUS ist COM1-NC1 geschlossen.\r\n\r\nG2000-Interlock-Test\r\n\r\n1. G2000 ausschalten.\r\n2. Den Jumper I1-I2 entfernen.\r\n3. Verdrahten: G2000 I1 -> COM1, G2000 I2 -> NO1.\r\n4. CH1 EIN lassen und den G2000 einschalten. Das Gerät sollte normal bereit sein und manuellen Start erlauben.\r\n5. CH1 AUS schalten. Der G2000 sollte interlock Fehler zeigen und Start bzw. HV verweigern oder stoppen.\r\n6. CH1 wieder EIN schalten. Der G2000 sollte wieder normal sein und manuellen Start erlauben.\r\n\r\nBetriebshinweise\r\n\r\n- Der Interlock-Testbereich in diesem Branch ist nur für Engineering-Validierung gedacht.\r\n- Die Software arbeitet mit HikmicroAnalyzer-Screenshot-OCR. HikmicroAnalyzer nicht minimieren und nicht verdecken.\r\n- Wenn OCR noch nicht bereit ist, Relais Dry Run aktiv lassen.\r\n- Auto-Reset in der Software schließt nur den Interlock wieder. Es garantiert keinen automatischen Plasma-Neustart.\r\n- Nach erfolgreicher Laborvalidierung kann diese branch-spezifische Test-UI wieder entfernt werden。",
        }
    };

    public static string Get(string language, string key)
    {
        if (Texts.TryGetValue(language, out var texts) && texts.TryGetValue(key, out var value))
        {
            return value;
        }

        return Texts["en"].TryGetValue(key, out var fallback) ? fallback : key;
    }
}

public sealed record LanguageOption(string Code, string DisplayName);
