namespace ReactorSoftInterlock.Wpf;

public static class UiText
{
    private static readonly Dictionary<string, Dictionary<string, string>> Texts = new()
    {
        ["en"] = new()
        {
            ["app.title"] = "G2000 Temperature Soft Interlock",
            ["app.subtitle"] = "HikmicroAnalyzer OCR -> 90 C trip -> USB relay interlock",
            ["label.status"] = "Status:",
            ["group.temperature"] = "Temperature",
            ["group.controls"] = "Controls",
            ["group.configuration"] = "Configuration",
            ["group.chart"] = "Temperature Trend",
            ["button.selectRoi"] = "Select ROI",
            ["button.start"] = "Start",
            ["button.stop"] = "Stop",
            ["button.reset"] = "Reset",
            ["button.testRelay"] = "Test Relay Stop",
            ["button.export"] = "Export CSV",
            ["button.save"] = "Save Settings",
            ["label.window"] = "Window",
            ["label.threshold"] = "Threshold C",
            ["label.tesseract"] = "Tesseract",
            ["label.interval"] = "Interval ms",
            ["label.com"] = "COM Port",
            ["label.baud"] = "Baud",
            ["label.stopHex"] = "Stop HEX",
            ["label.resetHex"] = "Reset HEX",
            ["label.language"] = "Language",
            ["label.recovery"] = "Recovery C",
            ["label.stable"] = "Stable sec",
            ["check.dryRun"] = "Dry run relay",
            ["check.autoReset"] = "Auto reset",
            ["grid.time"] = "Time",
            ["grid.temp"] = "Temp C",
            ["grid.status"] = "Status",
            ["grid.relay"] = "Relay",
            ["grid.reason"] = "Reason",
            ["grid.roi"] = "ROI",
            ["footer.ready"] = "Ready.",
            ["footer.monitoringStarted"] = "Monitoring started.",
            ["footer.monitoringStopped"] = "Monitoring stopped.",
            ["footer.settingsSaved"] = "Settings saved",
            ["footer.roiSaved"] = "ROI saved",
            ["footer.resetComplete"] = "Reset complete",
            ["footer.relayTestComplete"] = "Relay test completed",
            ["footer.csvExported"] = "CSV exported",
            ["footer.tripped"] = "TRIPPED: relay stop command sent.",
            ["footer.lastSample"] = "Last sample",
            ["message.resetBlocked"] = "Reset is allowed only after a valid temperature below the threshold is read.",
            ["message.resetBlockedTitle"] = "Reset blocked",
            ["status.Idle"] = "Idle",
            ["status.Monitoring"] = "Monitoring",
            ["status.NoReading"] = "No reading",
            ["status.Tripped"] = "Tripped",
            ["status.RelayTestFailed"] = "Relay test failed",
            ["chart.noData"] = "No valid temperature data yet",
            ["chart.threshold"] = "Trip",
            ["chart.recovery"] = "Recovery"
        },
        ["zh-CN"] = new()
        {
            ["app.title"] = "G2000 温度联控软锁",
            ["app.subtitle"] = "HikmicroAnalyzer OCR -> 90 C 停机 -> USB 继电器联锁",
            ["label.status"] = "状态：",
            ["group.temperature"] = "温度",
            ["group.controls"] = "控制",
            ["group.configuration"] = "配置",
            ["group.chart"] = "温度趋势",
            ["button.selectRoi"] = "框选 ROI",
            ["button.start"] = "开始",
            ["button.stop"] = "停止",
            ["button.reset"] = "复位",
            ["button.testRelay"] = "测试继电器停机",
            ["button.export"] = "导出 CSV",
            ["button.save"] = "保存设置",
            ["label.window"] = "窗口",
            ["label.threshold"] = "停机阈值 C",
            ["label.tesseract"] = "Tesseract",
            ["label.interval"] = "间隔 ms",
            ["label.com"] = "COM 口",
            ["label.baud"] = "波特率",
            ["label.stopHex"] = "Stop HEX",
            ["label.resetHex"] = "Reset HEX",
            ["label.language"] = "语言",
            ["label.recovery"] = "恢复阈值 C",
            ["label.stable"] = "稳定秒数",
            ["check.dryRun"] = "继电器 Dry Run",
            ["check.autoReset"] = "自动复位",
            ["grid.time"] = "时间",
            ["grid.temp"] = "温度 C",
            ["grid.status"] = "状态",
            ["grid.relay"] = "继电器",
            ["grid.reason"] = "原因",
            ["grid.roi"] = "ROI",
            ["footer.ready"] = "就绪。",
            ["footer.monitoringStarted"] = "监控已开始。",
            ["footer.monitoringStopped"] = "监控已停止。",
            ["footer.settingsSaved"] = "设置已保存",
            ["footer.roiSaved"] = "ROI 已保存",
            ["footer.resetComplete"] = "复位完成",
            ["footer.relayTestComplete"] = "继电器测试完成",
            ["footer.csvExported"] = "CSV 已导出",
            ["footer.tripped"] = "已 TRIP：继电器停机命令已发送。",
            ["footer.lastSample"] = "最新样本",
            ["message.resetBlocked"] = "只有读到低于阈值的有效温度后才允许复位。",
            ["message.resetBlockedTitle"] = "复位被阻止",
            ["status.Idle"] = "空闲",
            ["status.Monitoring"] = "监控中",
            ["status.NoReading"] = "无读数",
            ["status.Tripped"] = "已停机",
            ["status.RelayTestFailed"] = "继电器测试失败",
            ["chart.noData"] = "暂无有效温度数据",
            ["chart.threshold"] = "停机",
            ["chart.recovery"] = "恢复"
        },
        ["de"] = new()
        {
            ["app.title"] = "G2000 Temperatur-Soft-Interlock",
            ["app.subtitle"] = "HikmicroAnalyzer OCR -> 90 C Trip -> USB-Relais-Interlock",
            ["label.status"] = "Status:",
            ["group.temperature"] = "Temperatur",
            ["group.controls"] = "Steuerung",
            ["group.configuration"] = "Konfiguration",
            ["group.chart"] = "Temperaturverlauf",
            ["button.selectRoi"] = "ROI wählen",
            ["button.start"] = "Start",
            ["button.stop"] = "Stop",
            ["button.reset"] = "Reset",
            ["button.testRelay"] = "Relais-Stop testen",
            ["button.export"] = "CSV exportieren",
            ["button.save"] = "Einstellungen speichern",
            ["label.window"] = "Fenster",
            ["label.threshold"] = "Trip C",
            ["label.tesseract"] = "Tesseract",
            ["label.interval"] = "Intervall ms",
            ["label.com"] = "COM-Port",
            ["label.baud"] = "Baud",
            ["label.stopHex"] = "Stop HEX",
            ["label.resetHex"] = "Reset HEX",
            ["label.language"] = "Sprache",
            ["label.recovery"] = "Recovery C",
            ["label.stable"] = "Stabil s",
            ["check.dryRun"] = "Relais Dry Run",
            ["check.autoReset"] = "Auto-Reset",
            ["grid.time"] = "Zeit",
            ["grid.temp"] = "Temp C",
            ["grid.status"] = "Status",
            ["grid.relay"] = "Relais",
            ["grid.reason"] = "Grund",
            ["grid.roi"] = "ROI",
            ["footer.ready"] = "Bereit.",
            ["footer.monitoringStarted"] = "Überwachung gestartet.",
            ["footer.monitoringStopped"] = "Überwachung gestoppt.",
            ["footer.settingsSaved"] = "Einstellungen gespeichert",
            ["footer.roiSaved"] = "ROI gespeichert",
            ["footer.resetComplete"] = "Reset abgeschlossen",
            ["footer.relayTestComplete"] = "Relaistest abgeschlossen",
            ["footer.csvExported"] = "CSV exportiert",
            ["footer.tripped"] = "TRIPPED: Relais-Stop-Befehl gesendet.",
            ["footer.lastSample"] = "Letzter Messwert",
            ["message.resetBlocked"] = "Reset ist erst nach einem gültigen Temperaturwert unterhalb des Schwellwerts erlaubt.",
            ["message.resetBlockedTitle"] = "Reset blockiert",
            ["status.Idle"] = "Bereit",
            ["status.Monitoring"] = "Überwachung",
            ["status.NoReading"] = "Kein Messwert",
            ["status.Tripped"] = "Tripped",
            ["status.RelayTestFailed"] = "Relaistest fehlgeschlagen",
            ["chart.noData"] = "Noch keine gültigen Temperaturdaten",
            ["chart.threshold"] = "Trip",
            ["chart.recovery"] = "Recovery"
        }
    };

    public static string Get(string language, string key)
    {
        if (Texts.TryGetValue(language, out var texts) && texts.TryGetValue(key, out var value))
        {
            return value;
        }

        return Texts["en"].TryGetValue(key, out var fallback) ? fallback : key;
    }
}

public sealed record LanguageOption(string Code, string DisplayName);
